<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UE31D4N" failures="1" tests="1" name="Default test" time="13.862" errors="0" timestamp="2022-05-04T18:12:42 PDT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="11.678">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at dBFActions.ContactAction.sentMessageSuccessfully(ContactAction.java:52)
at dBFStepDefinations.ContactStepdef.validates_message_is_sent(ContactStepdef.java:57)
at âœ½.Validates message is sent(file:///C:/Users/12065/eclipse-workspace/DemoBlazeFinal/src/java/Resources/DBFFeatures/contact.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
